# Generated by Django 5.1.6 on 2025-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Sales Report'), ('low_stock', 'Low Stock Report')], max_length=20),
        ),
    ]
