# Generated by Django 5.1.6 on 2025-02-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_created_by_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
